# Julia — Introduction and Exercises for Students



**Learning objectives**
- recognize Julia’s basic types;
- work with vectors and matrices;
- define and call functions;
- use `if`, `for`, and `while`;
- use broadcasting, comprehensions, and iterators;
- understand the basics of multiple dispatch and composite types.




## 0. Environment Setup


In [1]:
using InteractiveUtils
using LinearAlgebra


## 1. Boolean Values and Logical Expressions

The `Bool` type has two values: `true` and `false`. The usual operators are `!`, `&&`, and `||`.


In [2]:
x = true
y = false

println(typeof(x))
println(x == y)
println(!x)
println(x && y)
println(x || y)


Bool
false
false
false
true


### Exercise 1
Define two Boolean variables `a` and `b`. Display the values of:
1. `a && b`
2. `a || b`
3. `!a`
4. an expression that checks whether exactly one of the two values is `true`.


In [4]:
a = false
b = true
a&&b, a||b, !a


(false, true, true)

## 2. Numbers and Operations

Julia distinguishes between integers and floating-point numbers. Standard arithmetic operations are directly available, including `^`, `%`, and `div`.


In [7]:
x = 5
y = 2

println(typeof(42))
println(typeof(42.0))
println(x + y)
println(x - y)
println(x * y)
println(x / y)
println(x ^ y)
println(x % y)
println(div(x, y))
println(div(x,y)*y+x%y) # catul intreg - quotinet



Int64
Float64
7
3
10
2.5
25
1
2
5


### Exercise 2
For `x = 17` and `y = 5`, compute:
- the sum, difference, and product;
- real division;
- integer quotient;
- remainder;
- `x^2 + y^2`.


In [11]:
x,y=17,5
@show sum, difference, product = x+y, x-y, x*y
@show real_div = x/y
@show quotient = div(x,y)
@show remainder = x%y
@show something = x^2+y^2



(sum, difference, product) = (x + y, x - y, x * y) = (22, 12, 85)
real_div = x / y = 3.4
quotient = div(x, y) = 3
remainder = x % y = 2
something = x ^ 2 + y ^ 2 = 314


314

## 3. Comparisons and the Ternary Operator


In [12]:
println(3 > 4)
println(3 <= 4)
println(3 < 4 < 5)

relu(x) = x > 0 ? x : 0
println(relu(-10))
println(relu(10))


false
true
true
0
10


### Exercise 3
Write a ternary expression that takes a number `x` and returns:
- `"positive"` if `x > 0`;
- `"non-positive"` otherwise.


In [14]:
# Scrieți soluția aici
x = -5
x > 0 ? "positive" : "non-positive"

"non-positive"

## 4. Strings


In [15]:
s = "optimal"
println(s)
println(typeof(s))


optimal
String


### Exercise 4
Create a string containing your name and display the variable type.


In [20]:
# Scrieți soluția aici
@show myname = "rodica"
typeof(myname)


myname = "rodica" = "rodica"


String

## 5. Vectors

Vectors are one-dimensional arrays. Julia uses **1-based indexing**.


In [21]:
v1 = zeros(3)
v2 = ones(3)
v3 = rand(3)
v4 = [3, 1, 4]
v5 = [3.1415, 1.618, 2.7182]

println(v4)
println(v5[1])
println(v5[end])
println(v5[end-1])


[3, 1, 4]
3.1415
2.7182
1.618


### 5.1 Slicing and Ranges


In [22]:
x = [1, 2, 5, 3, 1]
println(x[1:3])
println(x[1:2:end])
println(x[end:-1:1])


[1, 2, 5]
[1, 5, 1]
[1, 3, 5, 2, 1]


### 5.2 Modifying Vectors


In [23]:
x = [1, 2, 5, 3, 1]
push!(x, -1)
println(x)
pop!(x)
append!(x, [2, 3])
println(x)
sort!(x)
println(x)


[1, 2, 5, 3, 1, -1]
[1, 2, 5, 3, 1, 2, 3]
[1, 1, 2, 2, 3, 3, 5]


### Exercise 5
For `v = [4, 8, 15, 16, 23, 42]`:
1. display the first and last elements;
2. extract elements at positions 2–4;
3. reverse the elements using slicing;
4. append the value `100`;
5. remove the last element.


In [34]:
# Scrieți soluția aici
v = [4, 8, 15, 16, 23, 42]
@show v[[1,end]]
@show v[2:4]
@show v[end:-1:1]'
@show push!(v, 100)
@show pop!(v),v

v[[1, end]] = [4, 42]
v[2:4] = [8, 15, 16]
(v[end:-1:1])' = adjoint([42, 23, 16, 15, 8, 4])
push!(v, 100) = [4, 8, 15, 16, 23, 42, 100]
(pop!(v), v) = (100, [4, 8, 15, 16, 23, 42])


(100, [4, 8, 15, 16, 23, 42])

## 6. Broadcasting and Element-wise Operations

The dot `.` turns many operations into element-wise operations.


In [35]:
x = [1, 2]
y = [3, 4]

println(x + y)
println(x .* y)
println(x .^ 2)
println(sin.(x))
println(sqrt.(x))


[4, 6]
[3, 8]
[1, 4]
[0.8414709848078965, 0.9092974268256817]
[1.0, 1.4142135623730951]


### Exercise 6
For `x = [1,2,3,4,5]`, compute without an explicit loop:
- the square of each element;
- the square root of each element;
- `sin(x_i)` for each element;
- the vector `2x_i + 1`.


In [39]:
# Scrieți soluția aici
x = [1, 2, 3, 4, 5]
@show x.^2
@show sqrt.(x)
@show sin.(x)
@show 2 .* x.+1



x .^ 2 = [1, 4, 9, 16, 25]
sqrt.(x) = [1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979]
sin.(x) = [0.8414709848078965, 0.9092974268256817, 0.1411200080598672, -0.7568024953079282, -0.9589242746631385]
2 .* x .+ 1 = [3, 5, 7, 9, 11]


5-element Vector{Int64}:
  3
  5
  7
  9
 11

## 7. Copying versus Reference

When assigning a vector to another variable, both variables may refer to the same object. Use `copy` to create an independent copy.


In [40]:
x = [1, 2, 3]
y = x
y[1] = 4
println(x)

y = copy(x)
y[1] = 100
println("x = ", x)
println("y = ", y)


[4, 2, 3]
x = [4, 2, 3]
y = [100, 2, 3]


### Exercise 7
Create a vector `a`. Then create `b = a` and `c = copy(a)`. Modify the first element of `b` and `c`, and explain the observed result in a Markdown cell.


In [43]:
# Scrieți soluția aici
a = [5]
b = a
append!(a,[5,6])
@show b

b = [5, 5, 6]


3-element Vector{Int64}:
 5
 5
 6

## 8. Comprehensions

Comprehensions provide a compact way to construct vectors and matrices.


In [44]:
v = [sin(x) for x in 1:5]
println(v)

M = [sin(x + y) for x in 1:3, y in 1:2]
println(M)


[0.8414709848078965, 0.9092974268256817, 0.1411200080598672, -0.7568024953079282, -0.9589242746631385]
[0.9092974268256817 0.1411200080598672; 0.1411200080598672 -0.7568024953079282; -0.7568024953079282 -0.9589242746631385]


In [46]:
v = [x for x in 1:5]
println(v)

M = [x + y for x in 1:3, y in 100:102]
println(M)

[1, 2, 3, 4, 5]
[101 102 103; 102 103 104; 103 104 105]


### Exercise 8
Using comprehensions, construct:
1. the vector of squares of the numbers from 1 to 10;
2. the vector of even numbers from 2 to 20;
3. the matrix `A[i,j] = i + j`, for `i=1:4`, `j=1:3`.


In [52]:
# Scrieți soluția aici
@show x = [i^2 for i in 1:10]
@show y = [i for i in 2:2:20]
@show A = [i+j for i = 1:4, j=1:3]

x = [i ^ 2 for i = 1:10] = [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
y = [i for i = 2:2:20] = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
A = [i + j for i = 1:4, j = 1:3] = [2 3 4; 3 4 5; 4 5 6; 5 6 7]


4×3 Matrix{Int64}:
 2  3  4
 3  4  5
 4  5  6
 5  6  7

## 9. Matrices

Matrices are two-dimensional arrays. Elements in the same row are separated by spaces, and rows by `;`.


In [53]:
X = [1 2 3; 4 5 6; 7 8 9; 10 11 12]

println(X)
println(X[3,2])
println(X[1,:])
println(X[:,2])
println(X[1:2,1:2])


[1 2 3; 4 5 6; 7 8 9; 10 11 12]
8
[1, 2, 3]
[2, 5, 8, 11]
[1 2; 4 5]


### 9.1 Special Matrices and Linear Algebra


In [55]:
I3 = Matrix(1.0I(3))
D = Matrix(Diagonal([3, 2, 1]))
Z = zeros(3,2)
R = rand(3,2)

println(I3)
println(D)
println(R)
println(det([1 3; 3 1]))


[1.0 0.0 0.0; 0.0 1.0 0.0; 0.0 0.0 1.0]
[3 0 0; 0 2 0; 0 0 1]
[0.15902022024229368 0.5340349089330902; 0.39231102280402885 0.09708429965613563; 0.6117217146258581 0.5589383024154719]
-8.0


### Exercise 9
For the matrix `A = [1 2 3; 4 5 6; 7 8 10]`:
1. extract the second row;
2. extract the third column;
3. compute the transpose;
4. compute the determinant;
5. compute the inverse, if it exists.


In [62]:
# Scrieți soluția aici
A = [1 2 3; 4 5 6; 7 8 10]
@show A[2,:]
@show A[:,3]
@show A'
@show det(A)
@show inv(A)
@show inv(A)*A


A[2, :] = [4, 5, 6]
A[:, 3] = [3, 6, 10]
A' = [1 4 7; 2 5 8; 3 6 10]
det(A) = -3.000000000000001
inv(A) = [-0.6666666666666662 -1.333333333333333 0.9999999999999997; -0.6666666666666671 3.6666666666666656 -1.9999999999999993; 1.0000000000000002 -1.9999999999999996 0.9999999999999997]
inv(A) * A = [0.9999999999999994 0.0 2.220446049250313e-16; -6.661338147750939e-16 0.9999999999999982 -4.440892098500626e-16; -5.551115123125783e-16 0.0 1.0000000000000002]


3×3 Matrix{Float64}:
  1.0          0.0   2.22045e-16
 -6.66134e-16  1.0  -4.44089e-16
 -5.55112e-16  0.0   1.0

## 10. Linear Systems and Least Squares

The `\` operator efficiently solves linear systems and least-squares problems.


In [65]:
A = [1 0; 1 -2]
b = [32, -4]
x = A \ b
println(x)
println(A*x - b)

A2 = [1 2; 3 4; 5 6]
b2 = [0, 8, 9]
x2 = A2 \ b2
println(x2)
println(norm(A2*x2 - b2))


[32.0, 18.0]
[0.0, 0.0]
[3.3333333333333344, -1.083333333333334]
2.8577380332470406


### Exercise 10
Solve the system

\[
\begin{aligned}
2x + y &= 5\\
x - y &= 1
\end{aligned}
\]

using the `\` operator. Verify the solution by computing the residual `A*x - b`.


In [68]:
# Scrieți soluția aici
A = [2 1; 1 -1]
b =[5 ,1]
@show x = A\b 
@show A*x-b

x = A \ b = [2.0, 1.0]
A * x - b = [0.0, 0.0]


2-element Vector{Float64}:
 0.0
 0.0

## 11. Tuples and Named Tuples


In [69]:
t = (1, 0, [1, 2], 2.5029, 4.6692)
println(t[2])
println(t[end])

a, b = (1, 2)
println(a, " ", b)

nt = (a=1, b=-Inf)
println(nt.a)
println(merge(nt, (d=3, e=10)))


0
4.6692
1 2
1
(a = 1, b = -Inf, d = 3, e = 10)


### Exercise 11
Create a named tuple with the fields `name`, `age`, and `grade`. Display the value of the `grade` field separately.


In [ ]:
# Scrieți soluția aici
something = (name = "rodica", age = 100, grade = 1000)
println(something.grade)


1000


In [71]:
something.grade = 100

ErrorException: setfield!: immutable struct of type NamedTuple cannot be changed

## 12. Dictionaries


In [72]:
d = Dict(3=>4, 5=>1)
println(d[5])
println(haskey(d, 3))
println(haskey(d, 4))


1
true
false


### Exercise 12
Construct a dictionary whose keys are the names of three students and whose values are their grades. Display one student’s grade and check whether a fourth student appears in the dictionary.


In [74]:
# Scrieți soluția aici
my_dict = Dict("student1"=>10, "student2"=>13, "student3"=>67)
@show my_dict["student2"]
haskey(my_dict, "student4")

my_dict["student2"] = 13


false

## 13. Composite Types (`struct`)


In [75]:
struct Student
    name
    grade
end

s = Student("Ana", 9.5)
println(s.name)
println(s.grade)


Ana
9.5


### Exercise 13
Define a `Point2D` type with two fields, `x` and `y`. Create a point and compute its distance from the origin.


In [77]:
# Scrieți soluția aici
struct Point2D
    x
    y
end

@show distance = sqrt(point.x^2+point.y^2)

distance = sqrt(point.x ^ 2 + point.y ^ 2) = 5.0


5.0

## 14. Named and Anonymous Functions


In [78]:
function f(x, y)
    return x + y
end

f_compact(x, y) = x + y
h = x -> x^2 + 1

g(fun, a, b) = [fun(a), fun(b)]

println(f(3, 4))
println(f_compact(3, 0.1415))
println(h(3))
println(g(h, 5, 10))


7
3.1415
10
[26, 101]


### Exercise 14
Write:
1. a named function `square(x)`;
2. an anonymous function that computes `x^3 - 2x`;
3. apply the anonymous function to 1, 2, and 3 using broadcasting.


In [86]:
# Scrieți soluția aici
function square(x)
    return sqrt(x)
end

@show square(49)

anonymous = x -> x^3-2*x
[anonymous(i) for i in [1, 2, 3]]

square(49) = 7.0


3-element Vector{Int64}:
 -1
  4
 21

## 15. Optional and Keyword Arguments


In [84]:
f1(x=10) = x^2
f2(x, y, z=1) = x*y + z
f3(x, y=10; z=2) = (x+y)*z

println(f1())
println(f1(3))
println(f2(1,2))
println(f3(2, z=3))


100
9
3
36


In [91]:
f3(2,4,z=5)

30

### Exercise 15
Define `affine(x, a=1; b=0) = a*x + b`. Test the function with at least three different argument configurations.


In [92]:
# Scrieți soluția aici
affine(x, a=1; b=0) = a*x + b
affine(2,3,b=4),affine(2),affine(3,b=7)

(10, 2, 10)

## 16. Function overloading

In Julia, the same function can have different methods for different argument types.


In [101]:
dispatch_demo(x::Int64) = x + 10
dispatch_demo(x::Float64) = x + 3.1415

println(dispatch_demo(1))
println(dispatch_demo(1.0))


11
4.141500000000001


### Exercise 16
Define two methods for the function `describe`:
- for `Int64`, return `"integer"`;
- for `Float64`, return `"float"`.

Test both methods.


In [102]:
# Scrieți soluția aici
describe(x::Int64)="integer"
describe(x::Float64)="float"
describe(5), describe(5.0)

("integer", "float")

In [106]:
using AbstractTrees
AbstractTrees.children(d::DataType) = subtypes(d)
print_tree(Number)


Number
├─ MultiplicativeInverse
├─ Complex
├─ Measurement
└─ Real
   ├─ AbstractFloat
   │  ├─ BigFloat
   │  ├─ BFloat16
   │  ├─ Float16
   │  ├─ Float32
   │  └─ Float64
   ├─ AbstractIrrational
   │  ├─ Irrational
   │  └─ IrrationalConstant
   │     ├─ Fourinvπ
   │     ├─ Fourπ
   │     ├─ Halfπ
   │     ├─ Inv2π
   │     ├─ Inv4π
   │     ├─ Invsqrt2
   │     ├─ Invsqrt2π
   │     ├─ Invsqrtπ
   │     ├─ Invπ
   │     ├─ Log2π
   │     ├─ Log4π
   │     ├─ Loghalf
   │     ├─ Logten
   │     ├─ Logtwo
   │     ├─ Logπ
   │     ├─ Quartπ
   │     ├─ Sqrt2
   │     ├─ Sqrt2π
   │     ├─ Sqrt3
   │     ├─ Sqrt4π
   │     ├─ Sqrthalfπ
   │     ├─ Sqrtπ
   │     ├─ Twoinvπ
   │     ├─ Twoπ
   │     └─ Mad_constant
   ├─ FixedPoint
   ├─ Integer
   │  ├─ Bool
   │  ├─ OffsetInteger
   │  ├─ OffsetInteger
   │  ├─ Signed
   │  │  ├─ BigInt
   │  │  ├─ Int128
   │  │  ├─ Int16
   │  │  ├─ Int32
   │  │  ├─ Int64
   │  │  └─ Int8
   │  └─ Unsigned
   │     ├─ UInt128
   │     ├─ UInt16
 

## 17. Splatting


In [107]:
f(x, y, z) = x + y - z

a = [3, 1, 2]
b = (2, 2, 0)

println(f(a...))
println(f(b...))


2
4


In [108]:
f(a)

MethodError: MethodError: no method matching f(::Vector{Int64})
The function `f` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  f(::Any, !Matched::Any, !Matched::Any)
   @ Main ~/Library/CloudStorage/OneDrive-Personal/FSEGA/cursuri/2025-2026/erasmus ta/cod_ro_kl/I. Introduction to Optimization and Julia (1 h)/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y134sZmlsZQ==.jl:1
  f(::Any, !Matched::Any)
   @ Main ~/Library/CloudStorage/OneDrive-Personal/FSEGA/cursuri/2025-2026/erasmus ta/cod_ro_kl/I. Introduction to Optimization and Julia (1 h)/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y116sZmlsZQ==.jl:1


### Exercise 17
Define `volume(a,b,c) = a*b*c`. Store the dimensions in a tuple and call the function using `...`.


In [112]:
# Scrieți soluția aici
volume(a,b,c)=a*b*c
primul = [1,2,3]
doilea = (1,2,3)

volume(primul...), volume(doilea...)

(6, 6)

## 18. The `if` Statement


In [113]:
function compare_xy(x, y)
    if x < y
        return "x < y"
    elseif x > y
        return "x > y"
    else
        return "x = y"
    end
end

println(compare_xy(2, 5))


x < y


### Exercise 18
Write a function `sign_label(x)` that returns `"negative"`, `"zero"`, or `"positive"`.


In [116]:
# Scrieți soluția aici
function sign_label(x)
    if x<0
        return "$x is negative"
    elseif x>0
        return "$x is positive"
    else
        return "$x is zerrro"
    end
end

sign_label (generic function with 1 method)

In [117]:
sign_label(5)

"5 is positive"

## 19. The `while` Loop


In [118]:
X = [1, 2, 3, 4, 6, 8, 11, 13, 16, 18]
s = 0
Y = copy(X)
while !isempty(Y)
    s += pop!(Y)
end
println(s)


82


### Exercise 19
Use `while` to compute the sum of the numbers from 1 to 100.


In [121]:
# Scrieți soluția aici
s = 0
numbers = collect(1:100) # try first without collect

while !isempty(numbers)
    s +=pop!(numbers)
end

println(s)

5050


In [123]:
typeof(1:100), typeof(collect(1:100))

(UnitRange{Int64}, Vector{Int64})

## 20. The `for` Loop


In [124]:
X = [1, 2, 3, 4, 6, 8, 11, 13, 16, 18]
s = 0
for y in X
    s += y
end
println(s)

s2 = 0
for i = 1:length(X)
    s2 += X[i]
end
println(s2)


82
82


### Exercise 20
For `v = [3, -1, 4, -5, 2]`, use a `for` loop to compute:
- the sum of the elements;
- the number of positive elements;
- the maximum value without using `maximum`.


In [125]:
# Scrieți soluția aici
v = [3, -1, 4, -5, 2]
sum = 0
positive = 0
maximum = v[1]
for x in v
    sum+=x
    positive += x>0
    if x>maximum
        maximum = x
    end
end
@show sum positive maximum

sum = 3
positive = 3
maximum = 4


4

## 21. Iterators: `enumerate`, `eachindex`, `zip`


In [126]:
X = ["feed", "sing", "ignore"]
Y = [-5, -0.5, 0]

println(collect(enumerate(X)))
println(collect(eachindex(X)))
println(collect(zip(X, Y)))


[(1, "feed"), (2, "sing"), (3, "ignore")]
[1, 2, 3]
[("feed", -5.0), ("sing", -0.5), ("ignore", 0.0)]


### Exercise 21
Given the vectors `names = ["Ana", "Mihai", "Ioana"]` and `grades = [9.5, 8.0, 10.0]`, use `zip` to display messages such as `Ana -> 9.5`. Then use `enumerate` to display each student’s position.


In [132]:
# Scrieți soluția aici
names = ["Ana", "Mihai", "Ioana"]
grades = [9.5, 8.0, 10.0]
for (n,g) in zip(names, grades)
    println(n," => ",g)
end

for index in eachindex(names)
    println(index, "=>", names[index])
end

Ana => 9.5
Mihai => 8.0
Ioana => 10.0
1=>Ana
2=>Mihai
3=>Ioana


## 22. Cartesian Products and Subsets — Optional

These examples require the `IterTools` package for `subsets`.


In [133]:

using Pkg
Pkg.add("IterTools")


   Resolving package versions...
   Installed IterTools ─ v1.10.0
    Updating `~/.julia/environments/v1.12/Project.toml`
  [c8e1da08] + IterTools v1.10.0
    Updating `~/.julia/environments/v1.12/Manifest.toml`
  [c8e1da08] + IterTools v1.10.0
Precompiling packages...
    865.1 ms  ✓ IterTools
  1 dependency successfully precompiled in 2 seconds. 214 already precompiled.


MethodError: MethodError: no method matching delete!(::Int64)
The function `delete!` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  delete!(!Matched::BitSet, !Matched::Int64)
   @ Base bitset.jl:280
  delete!(!Matched::BitSet, !Matched::Integer)
   @ Base bitset.jl:281
  delete!(!Matched::DataStructures.IntSet, !Matched::Integer)
   @ DataStructures ~/.julia/packages/DataStructures/IwRP2/src/int_set.jl:76
  ...


In [2]:

import IterTools: subsets
import Base.Iterators: product

X = ["feed", "sing", "ignore"]
Y = [-5, -0.5, 0]
println(collect(subsets(X)))
println(collect(subsets(Y)))
println(collect(product(X, Y)))


[String[], ["feed"], ["sing"], ["feed", "sing"], ["ignore"], ["feed", "ignore"], ["sing", "ignore"], ["feed", "sing", "ignore"]]
[Float64[], [-5.0], [-0.5], [-5.0, -0.5], [0.0], [-5.0, 0.0], [-0.5, 0.0], [-5.0, -0.5, 0.0]]
[("feed", -5.0) ("feed", -0.5) ("feed", 0.0); ("sing", -5.0) ("sing", -0.5) ("sing", 0.0); ("ignore", -5.0) ("ignore", -0.5) ("ignore", 0.0)]


### Exercise 22 — Optional
For the set `[:A, :B, :C, :D]`, generate all subsets and count them. Compare the result with the theoretical formula `2^n`.


In [8]:
# Scrieți soluția aici
x = [:A, :B, :C, :D]
typeof(x)
@show partsofx = collect(subsets(x))
length(partsofx), 2^4



partsofx = collect(subsets(x)) = [Symbol[], [:A], [:B], [:A, :B], [:C], [:A, :C], [:B, :C], [:A, :B, :C], [:D], [:A, :D], [:B, :D], [:A, :B, :D], [:C, :D], [:A, :C, :D], [:B, :C, :D], [:A, :B, :C, :D]]


(16, 16)

## 23. Packages in Julia

Packages can be installed and updated through `Pkg`. For class use, avoid reinstalling packages every time the notebook is run.


In [9]:

using Pkg
Pkg.add("Distributions")
Pkg.update()

using Distributions


   Resolving package versions...
   Installed Gamma ─────────────────── v1.1.0
   Installed Rmath_jll ─────────────── v0.5.2+0
   Installed PDMats ────────────────── v0.11.41
   Installed HypergeometricFunctions ─ v0.3.30
   Installed StatsFuns ─────────────── v2.2.1
   Installed Accessors ─────────────── v0.1.45
   Installed SpecialFunctions ──────── v2.8.3
   Installed Roots ─────────────────── v3.0.6
   Installed ConstructionBase ──────── v1.6.0
   Installed CompositionsBase ──────── v0.1.2
   Installed OpenSpecFun_jll ───────── v0.5.6+0
   Installed InverseFunctions ──────── v0.1.17
   Installed CommonSolve ───────────── v0.2.13
   Installed FillArrays ────────────── v1.17.0
   Installed Rmath ─────────────────── v0.9.0
   Installed QuadGK ────────────────── v2.11.3
   Installed Distributions ─────────── v0.25.130
  Installing 2 artifacts
   Installed artifact OpenSpecFun           162.9 KiB
   Installed artifact Rmath                 94.4 KiB
    Updating `~/.julia/environments/v1

# Integrative Problems


## Problem A — Vector Analysis
Write a function `vector_stats(x)` that takes a numeric vector and returns a named tuple with:
- `n`: number of elements;
- `sum`: sum;
- `mean`: mean computed manually;
- `min`: minimum;
- `max`: maximum.

Use at least one loop.


In [ ]:
# Scrieți soluția aici


## Problem B — Matrix–Vector Product
Manually implement the product of a matrix `A` and a vector `x` using two `for` loops. Compare the result with `A*x`.


In [ ]:
# Scrieți soluția aici
A = [1 2; 3 4; 5 6]
x = [2, -1]


## Problem C — Least Squares
Use the data

```julia
A = [1 1; 1 2; 1 3; 1 4]
b = [2.1, 2.9, 4.2, 5.1]
```

1. compute `θ = A \ b`;
2. interpret the two components of `θ` as the intercept and slope;
3. compute the predictions `A*θ`;
4. compute the residual norm.


In [ ]:
# Scrieți soluția aici
A = [1 1; 1 2; 1 3; 1 4]
b = [2.1, 2.9, 4.2, 5.1]


## Problem D — Small Discrete Optimization Exercise
Consider the function

\[
f(x) = (x-3)^2 + 1.
\]

Evaluate the function for all integer values `x` in the interval `-5:10` and identify the value that minimizes the function.

**Requirement:** use a comprehension for the values and then either a loop or suitable Julia functions to identify the minimum.


In [ ]:
# Scrieți soluția aici


## Final Challenge
Write a function `solve_and_report(A,b)` that:
1. checks whether the dimensions of `A` and `b` are compatible;
2. computes `x = A \ b`;
3. computes the residual `r = A*x - b`;
4. returns a named tuple containing the solution, residual norm, and problem dimensions.

Test the function on a square system and an overdetermined problem.


In [ ]:
# Scrieți soluția aici


---
## Instructor Note
Exercises 1–10 are introductory; 11–17 reinforce data structures and functions; 18–22 focus on control flow and iterators; the integrative problems can be used as homework, an assessed lab, or review material.
